# Generated by Django 3.0.5 on 2020-04-08 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('creationdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_start', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('datetime_end', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('need_hours', models.FloatField(blank=True, null=True, verbose_name='Необходимое время')),
                ('spent_hours', models.IntegerField(blank=True, null=True, verbose_name='Затраченое время')),
                ('in_time', models.BooleanField(verbose_name='Во время?')),
                ('comments', models.TextField(blank='True', null='True', verbose_name='Комментарии')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
