# Generated by Django 3.0.5 on 2020-04-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='closed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Закрыта ли задача'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='in_time',
            field=models.BooleanField(default=False, verbose_name='Во время?'),
        ),
    ]
