# Generated by Django 3.0.5 on 2020-04-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200413_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='closed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Закрыта ли задача'),
        ),
    ]
